// Auto-generated by sanitizeGeneratedFiles

const handler0 = async (context) => {
This handler will return a list of available resume templates.
}

const handler1 = async (context) => {
This handler will collect feedback from users about the generated resumes.
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  if (url.pathname.includes("route0")) return handler0(context);
  if (url.pathname.includes("route1")) return handler1(context);
}
